platform :ios, 8.0

def available_pods
    pod 'Tapsbook', :path => '../../'
    
    # photo picker, feel free to swap it with yours.
    pod 'TZImagePickerController', '~> 1.7.1'
    
    # Note the SlackTextViewController newer than 1.7 will cause an editor UI bug
    pod 'SlackTextViewController', '1.7'

#disabled for China build
#pod 'GoogleAnalytics', '3.14.0'
end


target :TapsbookDemo do
available_pods
end
